name: CI/CD
on:
  pudh:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{username}}
        password: ${{password}}
    - name: Build and push Docker image
      run: |
        docker build -t nyrahul/wisecow .
        docker tag nyrahul/wisecow:latest
        docker push nyrahul/wisecow:latest
    - name: Deploy to Kubernetes
      uses: Kubernetes/deploy-action@v1
      with:
        kubeconfig: ${{secrets.KUBECONFIG}}
        deployment: wisecow
        image: nyrahul/wisecow:latest
