apiVersion: v1
kind: Service
metadata:
  name: wisecow
spec:
  selector:
    app: wisecow
  ports:
  - name: http
    port: 80
    targetPort:3000
type: LoadBalancer
tls:
 - host:
  - (link unavailable)
  secretName: wisecow-tls
